# Generated by Django 6.0 on 2025-12-21 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('new', 'New Student'), ('senior', 'Senior Student')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=120)),
                ('program', models.CharField(max_length=120)),
                ('year', models.IntegerField(default=1)),
                ('id_card', models.FileField(blank=True, null=True, upload_to='documents/id_cards/')),
                ('grade_12_card', models.FileField(blank=True, null=True, upload_to='documents/grade8/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='documents/photos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
