# Generated by Django 6.0 on 2026-01-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade_12_card',
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_10_certificate',
            field=models.FileField(blank=True, null=True, upload_to='students/documents/grade10/'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_12_certificate',
            field=models.FileField(blank=True, null=True, upload_to='students/documents/grade12/'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='students/documents/transcript/'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='students/documents/id_card/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('distance', 'Distance Education'), ('extension', 'Extension')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('new', 'New Student'), ('continuing', 'Continuing Student')], max_length=15),
        ),
    ]
