# Generated by Django 6.0 on 2025-12-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('credit_hour', models.IntegerField()),
                ('material', models.FileField(blank=True, null=True, upload_to='course_materials/')),
            ],
        ),
    ]
