# Generated by Django 6.0 on 2026-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_add_course_request_payment_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='add_course_request',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='registration',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('add_course', 'Add Course')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
